[package]
name = "Projet_LEPAGE_TERRASSON"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"

serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
crossterm = "0.28.1"
